## src/main/BUILD

cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    deps = [
        "//src/function:function",
        "//src/BusRoute:BusRoute",
    ],
    data = ["//src/data:data"]
)
