
cc_library(
    name = "testFraction",
    srcs = ["testFraction.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Fraction:Fraction",
    ],
    visibility = ["//visibility:public"],
)