
cc_library(
    name = "testMatrix",
    srcs = ["testMatrix.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/MyMatrix:MyMatrix",
    ],
    visibility = ["//visibility:public"],
)