## src/main/BUILD

cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    data = ["//src/data:data"],
    deps = [
        "//src/Book:Book",
        "//src/Author:Author",
        "//src/Library:Library"
    ],
)
