
cc_library(
    name = "testList",
    srcs = ["testList.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/LinkedList:LinkedList",
    ],
    visibility = ["//visibility:public"],
)