cc_test(
    name = "tests",
    srcs = ["tests.cpp"],
    data = ["//src/data:data"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Author:Author",
        "//src/Book:Book",
        "//src/Library:Library",
    ]
)
