
cc_library(
    name = "session2student",
    srcs = ["session2student.cpp"],
    hdrs = ["session2student.hpp"],
        deps = ["//src/session1student:session1student"],
    visibility = ["//visibility:public"],
)
