
cc_test(
    name = "tests",
    srcs = ["tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/testFraction:testFraction",
        "//src/testList:testList",
        "//src/testMatrix:testMatrix",
        
    ]
)
