## src/function/BUILD

cc_library(
    name = "function",
    srcs = ["function.cpp"],
    hdrs = ["function.hpp"],
    deps = ["//src/BusRoute:BusRoute"],
    data = ["//src/data:data"],
    visibility = ["//visibility:public"],
)
