
cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    deps = [
        "//src/session1student:session1student",
        "//src/session2student:session2student",
        "//src/Student:Student",

    ],
)