## src/Book/BUILD

cc_library(
    name = "Book",
    srcs = ["Book.cpp"],
    hdrs = ["Book.hpp"],
    deps = ["//src/Author:Author"],
    data = ["//src/data:data"],
    visibility = ["//visibility:public"],
)
